music/urls.py
from django.conf.urls import url
from . import views

app_name ='music'

urlpatterns = [
	
     url(r'^register/$',views.UserFormView.as_view(),name='register'),

	#/music/
    url(r'^$',views.IndexView.as_view(),name='index'),
    
    #/music/18/
    url(r'^(?P<pk>[0-9]+)/$',views.DetailView.as_view(),name='detail'),


	#/music/album/add/
    url(r'album/add/$',views.AlbumCreate.as_view(),name='album-add'),

    #/music/album/2/
    url(r'album/(?P<pk>[0-9]+)/$',views.AlbumUpdate.as_view(),name='album-update'),

    #/music/album/2/delete
    url(r'album/(?P<pk>[0-9]+)/delete/$',views.AlbumDelete.as_view(),name='album-delete')

   ]

music/models.py
from django.db import models
from django.core.urlresolvers import reverse


class Album(models.Model):
	artist = models.CharField(max_length=250)
	album_title = models.CharField(max_length=250)
	genre = models.CharField(max_length=100)
	logo = models.FileField()

	def get_absolute_url(self):
		return reverse('music:detail',kwargs={'pk' :self.pk})

	def __str__(self):
		return	self.album_title + ' - ' + self.artist + ' - ' + self.genre


class Song(models.Model):
	album = models.ForeignKey(Album,on_delete=models.CASCADE)
	file_type = models.CharField(max_length=10)
	song_title = models.CharField(max_length=250)
	is_favourite = models.BooleanField(default=False)

	def __str__(self):
		return	self.song_title 

		

music/forms.py
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput)
	class Meta:
		model = User
		fields = ['username','email','password']

music/views.py
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.views.generic import View
from .models import Album
from .forms import UserForm

class IndexView(generic.ListView):
	template_name = 'music/index.html'
	context_object_name ='all_albums'
	
	def get_queryset(self):
		return Album.objects.all()

class DetailView(generic.DetailView):
	model = Album
	template_name = 'music/detail.html'

class AlbumCreate(CreateView):
	model = Album
	fields=['artist','album_title','genre','logo']

class AlbumUpdate(UpdateView):
	model = Album
	fields=['artist','album_title','genre','logo']

class AlbumDelete(DeleteView):
	model=Album
	success_url = reverse_lazy('music:index')

class UserFormView(View):
	form_class = UserForm
	template_name = 'music/registration_form.html'

	#dispaly blank form
	def get(self,request):
		form = self.form_class(None)
		return render(request, self.template_name,{'form':form})
    
    #process form data
	def post(self,request):
		form = self.form_class(request.POST)

		if form.is_valid():
			user = form.save(commit=False)

			#cleaned normalized 
			username = form.cleaned_data['username']
			password = form.cleaned_data['password']
			user.set_password(password)
			user.save()

			#returns user objects if credentials are correct
			user = authenticate(username=username,password=password)

			if user is not None:
				if user.is_active:
					login(request, user)
					return redirect('music:index')

		return render(request, self.template_name,{'form':form})

music/templates/album_form.html
{% extends 'music/base.html' %}
{% block title %}Add a New Album{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">
	<div class="row">
		<div class="col-sm-offset-3 col-sm-9 col-md-offset-3 col-md-6">
			<div class="panel panel-default">
				<div class="panel-body">
					<h3>Add a new Album</h3>
					{% if error_messgae %}
						<p><strong>{{ error_message }}</strong></p>
					{% endif %}
					<form class="for" action="" method="post" enctype="multipart/form-data">
						{% csrf_token %}
						{% include 'music/form-template.html' %}
						<div class="form-group">
							<div class="col-sm-offset-2 col-sm-10">
								<button type="submit" class="btn btn-success">Submit</button>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}

music/templates/base.html
<!doctype html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>{% block title %}Shakky{% endblock %}</title>
	{% load staticfiles %}
	<link rel="icon" type="image/png" href="{% static 'music/images/icon.png' %}">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<link href="https://fonts.googleapis.com/css?family=Permanent+Marker" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Cabin+Sketch" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="{% static 'music/main.css' %} ">
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
</head>
<body>
	<nav class="navbar navbar-inverse">
		<div class="container-fluid">
			<!--header-->
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#top">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="{% url 'music:index'%}">Shakky</a>
			</div>
			<!-- items -->
			<div class="collapse navbar-collapse" id="top">
				<ul class="nav navbar-nav">
					<li class="active">
						<a href="{% url 'music:index' %}">
								<span class="glyphicon glyphicon-cd " aria-hidden="true"></span>&nbsp; Albums
						</a>
					</li>
					<li class="">
						<a href="#">
								<span class="glyphicon glyphicon-music " aria-hidden="true"></span>&nbsp; Songs
						</a>
					</li>
				</ul>
				<form class="navbar-form navbar-left" role="search" method="get" action="#">
					<div class="form-group">
						<input type="text" class="form-control" name="query" value="" placeholder="search for the song">
					</div>
					<button type="submit" class="btn btn-default">Search</button>
				</form>
				<ul class="nav navbar-nav navbar-right">
					<li class="">
						<a href="#">
								<span class="glyphicon glyphicon-plus " aria-hidden="true"></span>&nbsp; Add Album
						</a>
					</li>
					<li class="">
						<a href="#">
								<span class="glyphicon glyphicon-off " aria-hidden="true"></span>&nbsp; Logout
						</a>
					</li>
				</ul>
			</div>
		</div>
	</nav>
	{% block new %}
	{% endblock %}
</body>
</html>

music/templates/detail.html
{% extends 'music/base.html' %}
{% block title %}Song Details{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body%}
<div class="container-fluid songs-container">
	<div class="row">
		<!-- left album info -->
		<div class="col-sm-4 col-md-3">
			<div class="panel panel-default">
				<div class="panel-body">
					<a href="{% url 'music:detail' album.id %}">
						{% if album.logo %}
						<img src="{{ album.logo }}" class="img-responsive">
						{% else %}
						<h3> No Image Art</h3>
						{% endif %}
					</a>
					<h2>{{ album.album_title }} <br><small>{{ album.genre }}</small></h2>
					<h3>{{ album.artist }}</h3>
				</div>
			</div>
		</div>

		<!--Right song info -->
		<div class="col-sm-8 col-md-9">
		<ul class="nav nav-pills" style="margin-botttom:10px" >
			<li role="presentation" class="active">
				<a href="{% url 'music:detail' album.id %}">View All</a>
			</li>
			<li role="presentaion"><a href="#">Add New Songs</a></li>
		</ul>

		<div class="panel panel-default">
			<div class="panel-body">
				<h3>All Songs</h3>

				{% if error_message %}
				<p><strong>{{ error_message}}</strong></p>
				{% endif %}

				<table class="table">
					<thead>
						<tr>
							<th>Song Title </th>
							<th>Audio File </th>
							<th>Favourite</th>
							<th> Actions</th>
						</tr>
					</thead>
					<tbody>
						{% for song in album.song_set.all %}
						<tr>
							<td>{{song.song_title}}</td>
							<td>
								<a target="_blank" href="{{ song.audio_file.url }}">
									<button type="button" class="btn btn-success btn-xs">
										<span class="glyphicon glyphicon-play"></span>&nbsp; Play
									</button>
								</a>
							</td>
							<td>
								<a href="{ % url 'music:favourite' song.id %}" class="btn-favourite">
									<span class="glyphicon glyphicon-star {% if song.is_favourite %}active{% endif %}"></span>
								</a>
							</td>
							<td>
								<form action="#" method="post" style="display :inline">
									{% csrf_token %}
									<input type="hidden" name="song_id" value="{{ song_id }}" />
									<button type="submit" class="btn btn-danger btn-sm">
										<span class="glyphicon glyphicon-remove"></span>&nbsp; Delete
									</button>
								</form>
							</td>
						</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>
{% endblock %}

music/templates/index.html
{% extends 'music/base.html' %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="albums-container container-fluid">
	<!-- Album -->
	<div class="row">
			<div class="col-sm-12">
				<h1 style="color:#999999;font-size:50px"><b>{{ user.username}}'s Albums </b></h1>
			</div>
			{% if all_albums %}
				{% for album in all_albums %}
				<div class="col-sm-4 col-lg-2">
					<div class="thumbnail">
						<a href="{% url 'music:detail' album.id %}">
							<img src="{{ album.logo }}" class="img-responsive">
						</a>
						<div class="caption">
							<h2>{{ album.album_title}}</h2>
							<h4>{{ album.artist }}</h4>

							<!-- View details -->
							<a href="{% url 'music:detail' album.id %}" class="btn btn-primary btn-sm" role="button">View Details </a>

							<form action="#" method="post" style="display :inline">
								{% csrf_token %}
								<input type="hidden" name="album_id" value="{{ album_id }}" />
								<button type="submit" class="btn btn-default btn-sm">
									<span class="glyphicon glyphicon-trash"></span>
								</button>
							</form>

							<!-- Favourite Album -->
							<a href="#" class="btn btn-default btn-sm btn-favourite">
								<span class="glyphicon glyphicon-star {%if album.is_favourite %}active{% endif %}">
							</a>
						</div>
					</div>
				</div>
				{% endfor %}
			{% else %}
				<div class="col-sm-12">
					<br>
					<a href="#">
						<button type="button" class="btn btn-success">
							<span class="glyphion glyphicon-plus"></span>&nbsp; Add Album
						</button>
					</a>
				</div>
			{% endif %}
	</div>

<!-- if user searches for song -->
	{% if songs %}
		<div class="row">
			<div class="col-sm-12">
				<h3>Songs</h3>
			</div>
				<div class="panel panel-default">
					<div class="panel-body">
						<table class="table">
							<thead>
								<tr>
									<th>Song Title </th>
									<th>Artist </th>
									<th>Audio File </th>
									<th>Album </th>
									<th>Favourite </th>
								</tr>
							</thead>
							<tbody>
								{% for songs in songs %}
								<tr>
									<td>{{song.song_title}}</td>
									<td>{{ song.album.artist }}</td>
									<td>
										<a target="_blank" href="{{ song.audio_file.url }}">
											<button type="button" class="btn btn-success btn-xs">
												<span class="glyphicon glyphicon-play"></span>&nbsp; Play
											</button>
										</a>
									</td>
									<td>
										<a href="{% url 'music:detail' song.album.id %}">
											<img src="{{ song.album.logo }}" class="img-responsive" style="width : 20px float:left; margin-right:10px"/>
										</a>
										<a href="{% url 'music:detail' song.song.album.id %}">{{ song.album.album_title}}
										</a>
									</td>
									<td>
										<a href="{ % url 'music:favourite' song.id %}" class="btn-favourite">
											<span class="glyphicon glyphicon-star {% if song.is_favorite %}active{% endif %}"></span>
										</a>
									</td>
								</tr>
								{% endfor %}
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
		{% endif %}
</div>
{% endblock %}

music/templates/registration_form.html
{% extends 'music/base.html' %}
{% block title %}Register{% endblock %}

{% block body %}
<div class="container-fluid">
	<div class="row">
		<div class="col-sm-offset-3 col-sm-9 col-md-offset-3 col-md-6">
			<div class="panel panel-default">
				<div class="panel-body">
					<h3>Register User</h3>
					{% if error_messgae %}
						<p><strong>{{ error_message }}</strong></p>
					{% endif %}
					<form class="for" action="" method="post" enctype="multipart/form-data">
						{% csrf_token %}
						{% include 'music/form-template.html' %}
						<div class="form-group">
							<div class="col-sm-offset-2 col-sm-10">
								<button type="submit" class="btn btn-success">Submit</button>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}